default:
    tags:
        - kazan-M

include:
    - project: "sdks/direct/templates"
      ref: main
      file: "php/php_release.yml"

variables:
    ENABLE_PACKAGE_MANAGER: "true"
    GITHUB_TOKEN: "${WL_GITHUB_TOKEN}"
    GITHUB_EMAIL: "${WL_GIT_EMAIL}"
    GITHUB_USERNAME: "${WL_GIT_USERNAME}"
    GITLAB_GROUP_URL: "${GITLAB_INTERNAL_URL}/sdks/direct/server-sdk/worldline-direct"
